---
- name: 'Gather facts on hosts'
  hosts: 'all'

  tasks:
    - name: 'Gather facts'
      ansible.builtin.setup: {}

    - name: 'Show Operating System'
      ansible.builtin.debug:
        msg: "My OS: {{ ansible_os_family ~ ' ' ~ ansible_distribution_version }}"
...
